use_frameworks!
pod 'Parse'
pod 'ParseUI'
pod 'Alamofire'
pod 'HanekeSwift'
pod 'GoogleMaps'
pod 'FBSDKCoreKit'
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod "FBSDKMessengerShareKit"
pod 'XLPagerTabStrip', '~> 5.0'
pod 'XLActionController'