platform :ios, '9.0'
use_frameworks!

pod 'Parse'
pod 'ParseUI'
pod 'Alamofire'
pod 'HanekeSwift'
pod 'GoogleMaps'
pod 'FBSDKCoreKit'
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod "FBSDKMessengerShareKit"
pod 'XLPagerTabStrip’
pod 'XLActionController'